# Generated by Django 6.1.2 on 2026-10-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_ai', '0003_agentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettings',
            name='ai_api_base',
            field=models.CharField(blank=True, help_text='در صورت نیاز به آدرس سفارشی (مثلاً http://localhost:11434/v1 یا https://api.avalai.ir/v1 یا OpenRouter)', max_length=255, verbose_name='آدرس اندپوینت / Base URL'),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='ai_api_key',
            field=models.CharField(blank=True, help_text='اکسس توکن یا کلید اختصاصی شما برای ارتباط با مدل.', max_length=255, verbose_name='اکسس توکن / کلید API (Access Token)'),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='ai_model',
            field=models.CharField(blank=True, default='gpt-4o-mini', help_text='مثال: gpt-4o-mini, claude-3-5-sonnet, deepseek-chat, gemini-1.5-flash, llama3', max_length=100, verbose_name='نام مدل (Model)'),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='ai_provider',
            field=models.CharField(choices=[('echo', 'Echo (تستی بدون نیاز به کلید)'), ('openai', 'OpenAI (ChatGPT)'), ('anthropic', 'Anthropic (Claude)'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('openrouter', 'OpenRouter'), ('mistral', 'Mistral AI'), ('groq', 'Groq'), ('ollama', 'Ollama (محلی / Local)'), ('custom', 'سایر / OpenAI Compatible')], default='echo', help_text='سرویس\u200cدهنده هوش مصنوعی مورد نظر را انتخاب کنید.', max_length=50, verbose_name='سرویس\u200cدهنده هوش مصنوعی (Provider)'),
        ),
    ]
