# Generated by Django 6.1.2 on 2026-10-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_ai', '0004_agentsettings_ai_api_base_agentsettings_ai_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsettings',
            name='ai_model',
            field=models.CharField(blank=True, default='gpt-4o-mini', help_text='مثال: gpt-4o-mini, claude-3-5-sonnet, deepseek-chat, gemini-3.8-flash, llama3', max_length=100, verbose_name='نام مدل (Model)'),
        ),
    ]
